name: Release Latest Chrome Extension Zip File
on:
  push:
    branches:
      - main
      - master

env:
  RELEASE_TAG: latest
  BUILD_FILE_PATH: build/chrome-mv3-prod.zip
  ASSET_LABEL: autobot.zip

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
          run_install: true
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
          cache: "pnpm"
      - name: Build the extension
        run: pnpm build
      - name: Package the extension into a zip artifact
        run: pnpm package
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ env.RELEASE_TAG }} ${{ env.BUILD_FILE_PATH }}#${{ env.ASSET_LABEL }} --clobber
